import { PartialType } from "@nestjs/mapped-types"

export enum Art {
    AGRI_ANI = 'Agriculture et Elevage',
    SCENE = 'Art de la scène',
    MARTIAL = 'Art martiaux',
    SING_DANCE = 'Chant et Danse',
    SEW_TAN = 'Couture et Tannerie',
    CROCHET = 'Crochetage',
    COOK_CUT = 'Cuisine et Dépeçage',
    WOOD = 'Ebenisterie',
    METAL = 'Métallurgie',
    BREW = 'Mixologie',
    MUSIC = 'Musique',
    NAV = 'Navigation',
    GOLDSMITH = 'Orfèvrerie',
    KNOT = 'Pratique des nœuds',
    SCULPT = 'Sculpture',
}

export enum Knowledge {
    ALCHIMY = 'Alchimie',
    ANATOMY = 'Anatomie',
    ASTRO = 'Astrologie et Astronomie',
    BIOLOGY = 'Biologie',
    HERBO = 'Botanique et Herbologie',
    ESO = 'Culture ésotérique',
    GEN = 'Culture générale',
    CHIM = 'Chimie',
    GEO = 'Géologie',
    HIST_GEO = 'Histoire et Géographie',
    LITT = 'Littérature et Poésie',
    MATH = 'Mathématiques',
    MECA = 'Mécanique',
    TRAD = 'Moeurs et Traditions',
    PHY = 'Physique',
    REL = 'Religion',
}

export enum Intellect {
    CRIT = 'Analyse critique',
    CONC = 'Concentration',
    CONSC = 'Conscience',
    RAIS = 'Deduction et Raisonnement',
    DETER = 'Détermination',
    EMPA = 'Empathie',
    STRESS = 'Gestion du stress',
    IMAG = 'Imagination',
    IMPRO = 'Improvisation',
    READ_WRITE = 'Lecture et Ecriture',
    FEEL = 'Maîtrise de ses émotions',
    MEMO = 'Mémoire',
    PHI = 'Philosophie',
    RETH = 'Rethorique et Répartie',
    RES = 'Résiliance',
    TEMP = 'Tempérament',
}

export enum Physical {
    ACCRO = 'Acrobatie',
    ARC = 'Archerie',
    COORD = 'Coordination',
    DIR = 'Corps à corps',
    DEMONSTRATION = 'Démonstration',
    DES = 'Destruction',
    ENDU = 'Endurance',
    EQUI = 'Eqiilibre',
    CLIMB = 'Escalade',
    ESCAPE = 'Esquive',
    INTRU = 'Intrusion',
    SWIM = 'Natation',
    PROJECTION = 'Projection',
    BREATH = 'Respiration',
    BEND = 'Souplesse',
}

export enum Social {
    COMMANDE = 'Commandement',
    COMMUNIC = 'Communication',
    CONVINCE = 'Convaincre',
    DEMAGO = 'Démagogie',
    DIPL = 'Diplomatie',
    DISSUADE = 'Dissuasion',
    EDUC = 'Education',
    ELOQ = 'Eloquence',
    CHEER = 'Encouragement',
    ESTIM = 'Estimation',
    HUM = 'Humour',
    INT = 'Intimidation',
    NEGO = 'Négociation',
    PEDA = 'Pédagogie',
    PROVOKE = 'Provocation',
    SEDUCE = 'Séduction',
}

export enum Survival {
    ENV = 'Analyse de l\'environnement',
    HIDE = 'Camouflage',
    CAMP = 'Campement',
    MAP = 'Cartographie',
    HUNT_FISH = 'Chasse et Pêche',
    CONSERVATION = 'Conservation des vivres',
    CRYPTOZ = 'Cryptozoologie',
    DISC = 'Discrétion et Furtivité',
    TAME = 'Dressage',
    DRUG = 'Drogues et Poisons',
    EQUIT = 'Equitation',
    ORIENT = 'Orientation',
    TRACK = 'Pistage',
    TRAP = 'Pose de pièges',
    VIGIL = 'Vigilance',
    ZOO = 'Zoologie',
}