export const ALL_WEAPONS =
    [
        {
            name: "Couteau",
            melee: true,
            category: 1,
            damage: "1D",
            attack: 0,
            defense: -5,
            twoHands: false,
        },
        {
            name: "Poignard d'Obsidienne",
            melee: true,
            category: 1,
            damage: "1D",
            attack: 0,
            defense: -4,
            twoHands: false,
        },
        {
            name: "Poignard",
            melee: true,
            category: 1,
            damage: "1D+1",
            attack: 0,
            defense: -4,
            twoHands: false,
        },
        {
            name: "Wakizashi",
            melee: true,
            category: 1,
            damage: "1D+2",
            attack: 0,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Dague",
            melee: true,
            category: 1,
            damage: "1D+2",
            attack: 0,
            defense: -2,
            twoHands: false,
        },
        {
            name: "Faucille",
            melee: true,
            category: 1,
            damage: "1D+2",
            attack: 0,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Fouet",
            melee: true,
            category: 1,
            damage: "1D",
            attack: 0,
            defense: -6,
            twoHands: false,
        },
        {
            name: "Boomerang",
            melee: true,
            category: 1,
            damage: "1D+2",
            attack: 0,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Faux",
            melee: true,
            category: 2,
            damage: "1D+3",
            attack: -1,
            defense: -4,
            twoHands: true,
        },
        {
            name: "Rapière",
            melee: true,
            category: 2,
            damage: "1D+3",
            attack: 0,
            defense: 0,
            twoHands: false,
        },
        {
            name: "Epée courte",
            melee: true,
            category: 2,
            damage: "1D+3",
            attack: 0,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Gourdin",
            melee: true,
            category: 2,
            damage: "1D+1",
            attack: -1,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Bâton",
            melee: true,
            category: 2,
            damage: "1D+1",
            attack: 0,
            defense: 0,
            twoHands: false,
        },
        {
            name: "Massue",
            melee: true,
            category: 2,
            damage: "1D+2",
            attack: 0,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Fléau",
            melee: true,
            category: 3,
            damage: "1D+3",
            attack: -1,
            defense: -5,
            twoHands: false,
        },
        {
            name: "Glaive",
            melee: true,
            category: 3,
            damage: "1D+2",
            attack: 0,
            defense: 0,
            twoHands: true,
        },
        {
            name: "Sabre",
            melee: true,
            category: 3,
            damage: "1D+3",
            attack: 0,
            defense: 0,
            twoHands: false,
        },
        {
            name: "Sabre d'abordage",
            melee: true,
            category: 3,
            damage: "1D+3",
            attack: 0,
            defense: -1,
            twoHands: false,
        },
        {
            name: "Masses d'armes",
            melee: true,
            category: 3,
            damage: "1D+4",
            attack: 0,
            defense: -2,
            twoHands: false,
        },
        {
            name: "Epée",
            melee: true,
            category: 3,
            damage: "1D+4",
            attack: 0,
            defense: 0,
            twoHands: false,
        },
        {
            name: "Katana",
            melee: true,
            category: 3,
            damage: "1D+4",
            attack: 1,
            defense: -1,
            twoHands: false,
        },
        {
            name: "Javelot",
            melee: true,
            category: 3,
            damage: "1D+3",
            attack: -1,
            defense: -4,
            twoHands: false,
        },
        {
            name: "Trident",
            melee: true,
            category: 3,
            damage: "1D+3",
            attack: -1,
            defense: -2,
            twoHands: false,
        },
        {
            name: "Hallebarde",
            melee: true,
            category: 4,
            damage: "1D+4",
            attack: -1,
            defense: -3,
            twoHands: true,
        },
        {
            name: "Pique",
            melee: true,
            category: 4,
            damage: "1D+5",
            attack: -1,
            defense: -4,
            twoHands: true,
        },
        {
            name: "Lance de Tournoi",
            melee: true,
            category: 4,
            damage: "1D+2",
            attack: 0,
            defense: -2,
            twoHands: false,
        },
        {
            name: "Lance de Combat",
            melee: true,
            category: 4,
            damage: "1D+6",
            attack: 0,
            defense: -3,
            twoHands: false,
        },
        {
            name: "Filet",
            melee: true,
            attack: 0,
            defense: -6,
            twoHands: false,
        },
        {
            name: "Lasso",
            melee: true,
            attack: 0,
            defense: 0,
            twoHands: false,
        },
        {
            name: "Fléau d'armes",
            melee: true,
            damage: "1D+5",
            attack: -1,
            defense: -4,
            twoHands: true,
        },
        {
            name: "Epée Bâtarde",
            melee: true,
            category: 5,
            damage: "1D+5",
            attack: -1,
            defense: -2,
            twoHands: true,
        },
        {
            name: "Epée à deux mains",
            melee: true,
            category: 5,
            damage: "1D+6",
            attack: -2,
            defense: -3,
            twoHands: true,
        },
        {
            name: "Nodachi",
            melee: true,
            category: 5,
            damage: "1D+6",
            attack: -1,
            defense: -3,
            twoHands: true,
        },
        {
            name: "Hache de Guerre",
            melee: true,
            category: 5,
            damage: "1D+4",
            attack: 0,
            defense: -2,
            twoHands: true,
        },
        {
            name: "Hache de Combat",
            melee: true,
            category: 5,
            damage: "2D+2",
            attack: -3,
            defense: -5,
            twoHands: true,
        },
        {
            name: "Marteau de Guerre",
            melee: true,
            category: 5,
            damage: "1D+6",
            attack: -2,
            defense: -3,
            twoHands: true,
        },
        {
            name: "Marteau de Combat",
            melee: true,
            category: 5,
            damage: "2D+5",
            attack: -3,
            defense: -4,
            twoHands: true,
        },
        {
            name: "Hache de jet",
            melee: false,
            damage: "1D+3",
            distance: 20,
            twoHands: false,
        },
        {
            name: "Fronde",
            melee: false,
            damage: "1D+2",
            distance: 30,
            twoHands: false,
        },
        {
            name: "Sarbacane",
            melee: false,
            damage: "Poison",
            distance: 15,
            twoHands: false,
        },
        {
            name: "Arc",
            melee: false,
            damage: "1D+4",  
            distance: 100,
            twoHands: true,
        },
        {
            name: "Grand Arc",
            melee: false,
            damage: "1D+5",
            distance: 200,
            twoHands: true,
        },
        {
            name: "Arbalète",
            melee: false,
            damage: "1D+6",
            distance: 60,
            twoHands: true,
        }
    ]